import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { PUSHWOOSH_SCRIPT } from '../config/pushwoosh.config';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="manifest" href="/manifest.json" />
        <script
          type="text/javascript"
          src="//cdn.pushwoosh.com/webpush/v3/pushwoosh-web-notifications.js"
          async
        ></script>

        <script
          dangerouslySetInnerHTML={{
            __html: PUSHWOOSH_SCRIPT
          }}
        />

        {/* <script
          dangerouslySetInnerHTML={{
            __html: `
              var Pushwoosh = window.Pushwoosh || [];
              Pushwoosh.push(['init', {
                  logLevel: 'info', // possible values: error, info, debug
                  applicationCode: '78A77-3DF89', // you application code from Pushwoosh Control Panel
                  // applicationCode: 'A8C74-9198A', // you application code from Pushwoosh Control Panel
                  safariWebsitePushID: 'web.com.example.domain', //  unique reverse-domain string, obtained in you Apple Developer Portal. Only needed if you send push notifications to Safari browser
                  defaultNotificationTitle: 'Pushwoosh', // sets a default title for push notifications
                  defaultNotificationImage: 'https://yoursite.com/img/logo-medium.png', // URL to custom custom notification image
                  autoSubscribe: true, // or true. If true, prompts a user to subscribe for pushes upon SDK initialization
                  subscribeWidget: {
                  enable: true
                  },
                  // userId: 'user_id', // optional, set custom user ID
                  // userId: '78A77-3DF89_3f7b3389-9a87-4d6d-ab1b-f841c701600a', // optional, set custom user ID
                  tags: {
                      // 'Name': 'John Smith'   	// optional, set custom Tags
                      'Name': 'PXMAN'   	// optional, set custom Tags
                  }										
              }]);
          `,
          }}
        /> */}
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
